"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Check, ImagePlus, LoaderCircle, Plus, Save, Trash2, Upload } from "lucide-react";
import { ApiError, createPortfolioItem, createReview, createService, deletePortfolioItem, deleteReview, deleteService, getPartnerOverview, publishPartner, updateAvailability, updateBookingConfig, updatePartnerProfile, updateSections, updateService, updateTheme, uploadMedia } from "@/lib/api/client";
import type { BookingConfig, Overview, PublicSite, Service, TemplateKey, ThemeConfig } from "@/lib/types";
import { SiteRenderer } from "@/components/public-site/site-renderer";
import { DashboardFrame } from "./dashboard-home";

type Tab = "brand" | "theme" | "content" | "services" | "gallery" | "reviews" | "booking";
const tabs: [Tab, string][] = [["brand", "Brand"], ["theme", "Theme"], ["content", "Content"], ["services", "Services"], ["gallery", "Gallery"], ["reviews", "Reviews"], ["booking", "Booking"]];
const colors = ["#26573d", "#8f5733", "#243873", "#73385c", "#1f1f1f"];

const editorPreview = (overview: Overview): PublicSite => ({ ...overview, metrics: { rating: overview.metrics.rating, reviewCount: overview.reviews.length, completedJobs: overview.metrics.bookingCount, views: overview.metrics.views } });
const displayError = (error: unknown) => error instanceof ApiError ? error.message : "We couldn’t save that change. Please try again.";

export function Editor() {
  const [overview, setOverview] = useState<Overview | null>(null); const [tab, setTab] = useState<Tab>("brand"); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const reload = () => getPartnerOverview().then(setOverview).catch((err) => setError(displayError(err)));
  useEffect(() => { reload(); const requested = new URLSearchParams(location.search).get("tab") as Tab | null; if (requested && tabs.some(([value]) => value === requested)) setTab(requested); }, []);
  const succeed = (message: string) => { setNotice(message); setError(""); setTimeout(() => setNotice(""), 2500); reload(); };
  const run = async (message: string, action: () => Promise<unknown>) => { setBusy(true); setError(""); try { await action(); succeed(message); } catch (err) { setError(displayError(err)); } finally { setBusy(false); } };
  if (!overview) return <DashboardFrame active="editor"><div className="dashboard-loading"><LoaderCircle className="spin"/> Loading editor…</div></DashboardFrame>;
  const preview = editorPreview(overview);
  return <DashboardFrame active="editor"><div className="editor-top"><div><h1>Edit your page</h1><p>Keep it simple. Change what customers notice.</p></div><div className="editor-top-actions"><a className="button secondary small" href={`/${overview.partner.slug}`} target="_blank">View page</a><button className="button small" onClick={() => run("Your Cleanie page is live.", publishPartner)} disabled={busy}>{overview.partner.status === "published" ? "Published" : "Publish"}</button></div></div><div className="editor-layout"><nav className="editor-nav" aria-label="Page editor">{tabs.map(([value, label]) => <button key={value} className={tab === value ? "active" : ""} onClick={() => setTab(value)}>{label}</button>)}</nav><section className="editor-panel"><div className="editor-panel-header"><h2>{tabs.find(([value]) => value === tab)?.[1]}</h2><p>{tab === "brand" ? "The identity customers recognize." : tab === "theme" ? "Choose a focused visual direction." : tab === "content" ? "Cleanie keeps the conversion order intact." : tab === "booking" ? "Control how customers request a clean." : "Keep the essentials current."}</p></div>{notice && <p className="editor-notice"><Check size={15}/>{notice}</p>}{error && <p className="form-error" role="alert">{error}</p>}{tab === "brand" && <BrandEditor overview={overview} busy={busy} onSave={(data) => run("Brand saved.", () => updatePartnerProfile(data))} onUpload={(file, purpose) => run("Image uploaded.", async () => { const result = await uploadMedia(file, purpose); await updatePartnerProfile(purpose === "profile" ? { profileImageUrl: result.url } : { heroImageUrl: result.url }); })}/>} {tab === "theme" && <ThemeEditor overview={overview} busy={busy} onSave={(value) => run("Theme saved.", () => updateTheme(value))}/>} {tab === "content" && <ContentEditor overview={overview} busy={busy} onSave={(sections) => run("Section visibility saved.", () => updateSections(sections))}/>} {tab === "services" && <ServicesEditor overview={overview} busy={busy} run={run}/>} {tab === "gallery" && <GalleryEditor overview={overview} busy={busy} run={run}/>} {tab === "reviews" && <ReviewsEditor overview={overview} busy={busy} run={run}/>} {tab === "booking" && <BookingEditor overview={overview} busy={busy} run={run}/>}</section><aside className="editor-preview"><span>LIVE PREVIEW</span><div className="preview-phone"><SiteRenderer site={preview} compact/></div></aside></div></DashboardFrame>;
}

function BrandEditor({ overview, busy, onSave, onUpload }: { overview: Overview; busy: boolean; onSave: (value: Record<string, string>) => void; onUpload: (file: File, purpose: "profile" | "hero") => void }) { const [slugState, setSlugState] = useState(overview.partner.slug); return <form className="editor-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); onSave({ businessName: String(form.get("businessName")), tagline: String(form.get("tagline")), serviceArea: String(form.get("serviceArea")), about: String(form.get("about")), slug: slugState }); }}><div className="image-upload-row"><label className="image-upload">{overview.partner.profileImageUrl ? <img src={overview.partner.profileImageUrl} alt="Current profile"/> : <Upload size={21}/>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => event.target.files?.[0] && onUpload(event.target.files[0], "profile")}/><span>Profile photo</span></label><label className="image-upload wide">{overview.partner.heroImageUrl ? <img src={overview.partner.heroImageUrl} alt="Current hero"/> : <ImagePlus size={21}/>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => event.target.files?.[0] && onUpload(event.target.files[0], "hero")}/><span>Hero image</span></label></div><label>Business name<input name="businessName" defaultValue={overview.partner.businessName} required/></label><label>Your Cleanie link<div className="slug-input"><span>cleanie.app/</span><input value={slugState} onChange={(event) => setSlugState(event.target.value.toLowerCase().replace(/\s+/g, "-"))} required/></div></label><label>Tagline<input name="tagline" defaultValue={overview.partner.tagline} required/></label><label>Service area<input name="serviceArea" defaultValue={overview.partner.serviceArea} required/></label><label>About your business<textarea name="about" rows={4} defaultValue={overview.partner.about || ""} placeholder="A short, welcoming introduction."/></label><button className="button" disabled={busy}><Save size={16}/> Save brand</button></form>; }

function ThemeEditor({ overview, busy, onSave }: { overview: Overview; busy: boolean; onSave: (value: { template?: TemplateKey; theme?: ThemeConfig }) => void }) { const [theme, setTheme] = useState<ThemeConfig>(overview.site.theme); const [template, setTemplate] = useState<TemplateKey>(overview.site.template); return <form className="editor-form" onSubmit={(event) => { event.preventDefault(); onSave({ template, theme }); }}><fieldset><legend>Template</legend><div className="choice-row">{(["clean", "warm-home", "pro"] as TemplateKey[]).map((value) => <button type="button" className={template === value ? "selected" : ""} key={value} onClick={() => setTemplate(value)}>{value === "warm-home" ? "Warm Home" : value[0].toUpperCase() + value.slice(1)}</button>)}</div></fieldset><fieldset><legend>Brand color</legend><div className="color-row">{colors.map((color) => <button type="button" className={theme.primaryColor === color ? "selected" : ""} key={color} style={{ backgroundColor: color }} onClick={() => setTheme({ ...theme, primaryColor: color })}><span className="sr-only">Use {color}</span></button>)}</div></fieldset><fieldset><legend>Typography</legend><div className="choice-row"><button type="button" className={theme.fontPreset === "modern" ? "selected" : ""} onClick={() => setTheme({ ...theme, fontPreset: "modern" })}>Modern</button><button type="button" className={theme.fontPreset === "soft" ? "selected" : ""} onClick={() => setTheme({ ...theme, fontPreset: "soft" })}>Soft</button></div></fieldset><fieldset><legend>Button shape</legend><div className="choice-row"><button type="button" className={theme.buttonStyle === "soft" ? "selected" : ""} onClick={() => setTheme({ ...theme, buttonStyle: "soft" })}>Soft</button><button type="button" className={theme.buttonStyle === "pill" ? "selected" : ""} onClick={() => setTheme({ ...theme, buttonStyle: "pill" })}>Pill</button></div></fieldset><button className="button" disabled={busy}><Save size={16}/> Save theme</button></form>; }

function ContentEditor({ overview, busy, onSave }: { overview: Overview; busy: boolean; onSave: (value: Overview["site"]["sections"]) => void }) { const [sections, setSections] = useState(overview.site.sections); const labels: [keyof typeof sections, string, string][] = [["services", "Services", "What customers can book"], ["portfolio", "Before & after", "Show your work"], ["reviews", "Google reviews", "Social proof from customers"], ["about", "About", "A short introduction"]]; return <form className="editor-form" onSubmit={(event) => { event.preventDefault(); onSave(sections); }}><p className="editor-helper">Turn sections on or off. Their order stays optimized by Cleanie.</p><div className="toggle-list">{labels.map(([key, title, description]) => <label key={key}><span><b>{title}</b><small>{description}</small></span><input type="checkbox" checked={sections[key]} onChange={() => setSections({ ...sections, [key]: !sections[key] })}/><i/></label>)}</div><button className="button" disabled={busy}><Save size={16}/> Save sections</button></form>; }

function ServicesEditor({ overview, busy, run }: { overview: Overview; busy: boolean; run: (message: string, action: () => Promise<unknown>) => void }) { const [adding, setAdding] = useState(false); const [draft, setDraft] = useState({ name: "", description: "", priceCents: "", durationMinutes: "120" }); const add = (event: React.FormEvent) => { event.preventDefault(); run("Service added.", async () => { await createService({ name: draft.name, description: draft.description, priceCents: Number(draft.priceCents) * 100, durationMinutes: Number(draft.durationMinutes), active: true }); setAdding(false); setDraft({ name: "", description: "", priceCents: "", durationMinutes: "120" }); }); }; return <div className="manage-list">{overview.services.map((service) => <ServiceRow service={service} key={service.id} busy={busy} run={run}/>) }{adding ? <form className="inline-form" onSubmit={add}><input placeholder="Service name" value={draft.name} required onChange={(event) => setDraft({ ...draft, name: event.target.value })}/><input placeholder="Description" value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })}/><input type="number" min="0" placeholder="Price ($)" value={draft.priceCents} required onChange={(event) => setDraft({ ...draft, priceCents: event.target.value })}/><input type="number" min="15" step="15" placeholder="Minutes" value={draft.durationMinutes} required onChange={(event) => setDraft({ ...draft, durationMinutes: event.target.value })}/><button className="button small" disabled={busy}>Add service</button></form> : <button className="text-action" onClick={() => setAdding(true)}><Plus size={16}/> Add service</button>}</div>; }
function ServiceRow({ service, busy, run }: { service: Service; busy: boolean; run: (message: string, action: () => Promise<unknown>) => void }) { const [edit, setEdit] = useState(false); const [draft, setDraft] = useState({ name: service.name, description: service.description, price: String(service.priceCents / 100), duration: String(service.durationMinutes) }); return <article className="manage-card">{edit ? <><input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })}/><input value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })}/><div className="compact-fields"><input type="number" value={draft.price} onChange={(event) => setDraft({ ...draft, price: event.target.value })}/><input type="number" value={draft.duration} onChange={(event) => setDraft({ ...draft, duration: event.target.value })}/></div><button className="button small" disabled={busy} onClick={() => run("Service saved.", async () => { await updateService(service.id, { name: draft.name, description: draft.description, priceCents: Number(draft.price) * 100, durationMinutes: Number(draft.duration) }); setEdit(false); })}>Save</button></> : <><div><b>{service.name}</b><small>{service.description || `${service.durationMinutes} min`} · ${(service.priceCents / 100).toFixed(0)}{!service.active && " · Hidden"}</small></div><div className="card-actions"><button onClick={() => setEdit(true)}>Edit</button><button onClick={() => run(service.active ? "Service hidden." : "Service shown.", () => updateService(service.id, { active: !service.active }))}>{service.active ? "Hide" : "Show"}</button><button aria-label={`Delete ${service.name}`} onClick={() => run("Service deleted.", () => deleteService(service.id))}><Trash2 size={15}/></button></div></>}</article>; }

function GalleryEditor({ overview, busy, run }: { overview: Overview; busy: boolean; run: (message: string, action: () => Promise<unknown>) => void }) { const [before, setBefore] = useState(""); const [after, setAfter] = useState(""); const [caption, setCaption] = useState(""); const select = (file: File, purpose: "before" | "after") => run("Image uploaded.", async () => { const image = await uploadMedia(file, purpose); purpose === "before" ? setBefore(image.url) : setAfter(image.url); }); return <div className="manage-list"><p className="editor-helper">Upload a real before and after pair. Both images are shown together on your page.</p><div className="gallery-drop-row"><label className="upload-box">{before ? <img src={before} alt="Before upload"/> : <><Upload size={22}/><span>Upload before</span></>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => event.target.files?.[0] && select(event.target.files[0], "before")}/></label><label className="upload-box">{after ? <img src={after} alt="After upload"/> : <><Upload size={22}/><span>Upload after</span></>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => event.target.files?.[0] && select(event.target.files[0], "after")}/></label></div><input placeholder="Caption (optional)" value={caption} onChange={(event) => setCaption(event.target.value)}/><button className="button" disabled={busy || !before || !after} onClick={() => run("Before & after added.", async () => { await createPortfolioItem({ beforeImageUrl: before, afterImageUrl: after, caption }); setBefore(""); setAfter(""); setCaption(""); })}><Plus size={16}/> Add before & after</button>{overview.portfolio.map((item) => <article className="portfolio-row" key={item.id}><img src={item.beforeImageUrl} alt="Before"/><img src={item.afterImageUrl} alt="After"/><span>{item.caption}</span><button aria-label="Delete portfolio item" onClick={() => run("Portfolio item deleted.", () => deletePortfolioItem(item.id))}><Trash2 size={15}/></button></article>)}</div>; }

function ReviewsEditor({ overview, busy, run }: { overview: Overview; busy: boolean; run: (message: string, action: () => Promise<unknown>) => void }) { const [adding, setAdding] = useState(false); return <div className="manage-list">{overview.reviews.map((review) => <article className="manage-card" key={review.id}><div><b>{review.author} · {"★".repeat(review.rating)}</b><small>{review.text}</small></div><button aria-label={`Delete review by ${review.author}`} onClick={() => run("Review deleted.", () => deleteReview(review.id))}><Trash2 size={15}/></button></article>)}{adding ? <form className="inline-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); run("Review added.", async () => { await createReview({ author: String(form.get("author")), rating: Number(form.get("rating")), text: String(form.get("text")), source: "manual", featured: overview.reviews.length === 0 }); setAdding(false); }); }}><input name="author" placeholder="Customer name" required/><select name="rating" defaultValue="5"><option value="5">5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option></select><textarea name="text" placeholder="What did they say?" required rows={3}/><button className="button small" disabled={busy}>Add review</button></form> : <button className="text-action" onClick={() => setAdding(true)}><Plus size={16}/> Add review</button>}</div>; }

function BookingEditor({ overview, busy, run }: { overview: Overview; busy: boolean; run: (message: string, action: () => Promise<unknown>) => void }) { const [config, setConfig] = useState<BookingConfig>(overview.booking); const [availability, setAvailability] = useState(overview.availability); const dayLabels = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]; const save = () => run("Booking settings saved.", async () => { await updateAvailability(availability); await updateBookingConfig(config); }); return <form className="editor-form" onSubmit={(event) => { event.preventDefault(); save(); }}><fieldset><legend>Days available</legend><div className="day-picker">{dayLabels.map((label, day) => <button type="button" className={availability.weekdays.includes(day) ? "selected" : ""} key={label} onClick={() => setAvailability({ ...availability, weekdays: availability.weekdays.includes(day) ? availability.weekdays.filter((item) => item !== day) : [...availability.weekdays, day].sort() })}>{label}</button>)}</div></fieldset><div className="form-grid"><label>Start time<input type="time" value={availability.startTime} onChange={(event) => setAvailability({ ...availability, startTime: event.target.value })}/></label><label>End time<input type="time" value={availability.endTime} onChange={(event) => setAvailability({ ...availability, endTime: event.target.value })}/></label></div><label>Booking CTA<input value={config.ctaLabel} onChange={(event) => setConfig({ ...config, ctaLabel: event.target.value })}/></label><fieldset><legend>Customer details</legend><div className="toggle-list compact">{(["name", "phone", "email", "address", "notes"] as const).map((field) => <label key={field}><span><b>{field[0].toUpperCase() + field.slice(1)}</b></span><input disabled={field === "name"} type="checkbox" checked={config.requiredFields[field]} onChange={() => setConfig({ ...config, requiredFields: { ...config.requiredFields, [field]: !config.requiredFields[field] } })}/><i/></label>)}</div></fieldset><fieldset><legend>Payment</legend><label className="radio-option"><input type="radio" checked={config.paymentMode === "none"} onChange={() => setConfig({ ...config, paymentMode: "none" })}/> No online payment</label><label className="radio-option muted"><input type="radio" disabled/> Deposit (coming later)</label><label className="radio-option muted"><input type="radio" disabled/> Full payment (coming later)</label></fieldset><label>Confirmation message<textarea rows={3} value={config.confirmationMessage} onChange={(event) => setConfig({ ...config, confirmationMessage: event.target.value })}/></label><button className="button" disabled={busy}><Save size={16}/> Save booking settings</button></form>; }
