import type { CSSProperties } from "react";
import { BadgeCheck, CalendarDays, MapPin, ShieldCheck, Star } from "lucide-react";
import type { PublicSite, Service } from "@/lib/types";
import { BookingFlow } from "./booking-flow";

const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(cents / 100);
const duration = (minutes: number) => minutes >= 60 ? `${Math.floor(minutes / 60)}–${Math.ceil(minutes / 60) + 1} hr` : `${minutes} min`;
const firstReview = (site: PublicSite) => site.reviews.find((review) => review.featured) ?? site.reviews[0];

function Rating({ site, short = false }: { site: PublicSite; short?: boolean }) { return <div className="site-rating"><Star size={short ? 13 : 15} fill="currentColor"/> <span>{site.metrics.rating.toFixed(1)} {short ? "Google" : `· ${site.metrics.reviewCount} Google reviews`}</span></div>; }
function Services({ services, variant }: { services: Service[]; variant: "clean" | "warm" | "pro" }) { return <section className={`site-services ${variant}`} aria-labelledby="services-title"><h2 id="services-title">{variant === "warm" ? "Choose what you need" : "Services"}</h2><div className="service-grid">{services.filter((service) => service.active).map((service) => <article className="site-service" key={service.id}><div><h3>{service.name}</h3><p>{service.description || duration(service.durationMinutes)}</p></div><strong>{variant === "warm" ? `from ${money(service.priceCents)}` : `${money(service.priceCents)}+`}</strong></article>)}</div></section>; }
function Proof({ site }: { site: PublicSite }) { const portfolio = site.portfolio[0]; if (!portfolio) return null; return <section className="site-proof" aria-labelledby="proof-title"><h2 id="proof-title">Work you can see</h2><figure><div><img src={portfolio.beforeImageUrl} alt={`Before: ${portfolio.caption || "cleaning work"}`}/><span>Before</span></div><div><img src={portfolio.afterImageUrl} alt={`After: ${portfolio.caption || "cleaning work"}`}/><span>After</span></div></figure>{portfolio.caption && <p>{portfolio.caption}</p>}</section>; }
function ReviewCard({ site }: { site: PublicSite }) { const review = firstReview(site); if (!review) return null; return <section className="site-review" aria-labelledby="review-title"><h2 id="review-title">{site.site.template === "warm-home" ? "Loved by local families" : site.site.template === "pro" ? "Recent customer review" : `Why customers choose ${site.partner.businessName.split(" ")[0]}`}</h2><article><div className="review-stars">★★★★★</div><blockquote>“{review.text}”</blockquote><cite>— {review.author} · {review.source === "google" ? "Google" : "Customer"}</cite></article></section>; }
function About({ site }: { site: PublicSite }) { if (!site.partner.about) return null; return <section className="site-about"><h2>About {site.partner.businessName}</h2><p>{site.partner.about}</p></section>; }
function SiteHero({ site, template }: { site: PublicSite; template: "clean" | "warm-home" | "pro" }) { const hero = site.partner.heroImageUrl || site.partner.profileImageUrl; const cta = site.booking.ctaLabel || (template === "warm-home" ? "See available times" : template === "pro" ? "Get an available slot" : "Book a cleaning"); if (template === "warm-home") return <header className="site-hero warm"><h1>{site.partner.businessName}</h1><p className="hero-tagline">{site.partner.tagline}</p>{hero && <div className="hero-image"><img src={hero} alt={`${site.partner.businessName} team`}/><Rating site={site} short/></div>}<h2>A clean home, without the stress.</h2><p className="area"><MapPin size={13}/>{site.partner.serviceArea}</p><a className="site-button" href="#book">{cta}</a></header>;
  if (template === "pro") return <header className="site-hero pro">{hero && <img className="hero-background" src={hero} alt=""/>}<div className="hero-shade"/><div className="hero-content"><span className="verified"><BadgeCheck size={13}/> VERIFIED TEAM</span><h1>{site.partner.businessName}</h1><p>{site.partner.tagline}</p><Rating site={site}/></div><a className="site-button" href="#book">{cta}</a></header>;
  return <header className="site-hero clean">{hero && <img className="hero-background" src={hero} alt=""/>}<div className="hero-shade"/><div className="hero-content"><h1>{site.partner.businessName}</h1><Rating site={site}/></div><p className="clean-tagline">{site.partner.tagline} <span><MapPin size={13}/>{site.partner.serviceArea}</span></p><a className="site-button" href="#book">{cta}</a></header>; }

export function SiteRenderer({ site, compact = false }: { site: PublicSite; compact?: boolean }) {
  const template = site.site.template;
  const style = { "--brand-primary": site.site.theme.primaryColor, "--button-radius": site.site.theme.buttonStyle === "pill" ? "999px" : "14px", "--site-bg": template === "warm-home" ? "#fcf6eb" : template === "pro" ? "#f4f6fb" : "#f9faf7", "--site-font": site.site.theme.fontPreset === "soft" ? "var(--font-lora)" : "var(--font-manrope)" } as CSSProperties;
  const serviceVariant = template === "warm-home" ? "warm" : template === "pro" ? "pro" : "clean";
  return <main className={`public-site template-${template} ${compact ? "site-compact" : ""}`} style={style}><SiteHero site={site} template={template}/><div className="site-content">{template === "clean" && <p className="intro-line">Professional cleaning, made easy.</p>}{site.site.sections.services && <Services services={site.services} variant={serviceVariant}/>} {template === "pro" && <section className="pro-metrics"><div><b>{site.metrics.reviewCount}</b><span>reviews</span></div><div><b>{site.partner.serviceArea || "15 mi"}</b><span>service area</span></div><div><b>{site.availability.weekdays.length} days</b><span>available</span></div></section>}{site.site.sections.portfolio && <Proof site={site}/>} {site.site.sections.reviews && <ReviewCard site={site}/>} {site.site.sections.about && <About site={site}/>} {!compact && <BookingFlow site={site}/>}</div>{!compact && <footer className="site-footer"><ShieldCheck size={14}/> Powered by Cleanie</footer>}</main>;
}
